### ISSUE TITLE
Force all components to have a capital as the first letter of the name and file name

### ISSUE THREAD

**Issue by eatrocks** [Jarvis1010/react-component-inator#3]
How do you feel about forcing the first letter of all components to have a capital first letter for their component name and file name?
This would include even containers, besides components, and views.
So if I asked for a component named `bruce` you would create a component named `Bruce`
Having a capital first letter of a component name is common and a suggested best practice.

**Comment by Jarvis1010** [comment]
Feature added in 1.3.0
